### PR TITLE
Refactor resource instance and documentations

### PR DESCRIPTION
**Pull request by Diptipowervs**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Relates OR Closes #0000

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccXXX'

...
```

### CODE REVIEW

**Comment by Diptipowervs** [comment]
PASS
testing: warning: no tests to run

**Comment by michaelkad** [comment]
> PASS testing: warning: no tests to run

Test should have run unless your config are not setup correctly

**Review by michaelkad — CHANGES_REQUESTED** [review]
Some of those file should've not been modify. Could you sync this branch or create a new PR with only your changes ?
Screenshot 2024-03-25 at 1 33 59 PM

**Comment by Diptipowervs** [comment]
Closing PR since too many files changed

**Pull request closed without merging**
